services:
  timestream-prometheus-connector:
    container_name: connector
    build: .
    ports:
      - "9201:9201"
    volumes:
      - .:/home
    command:
      - --default-database=CorrDB
      - --default-table=CorrMetrics
      - --region=us-west-2
      - --log.level=debug
