services:
  timestream-prometheus-connector:
    container_name: connector
    build: .
    ports:
      - "9201:9201"
    volumes:
      - .:/home
    command:
      - --default-database=${DEFAULT_DATABASE:-PrometheusDatabase}
      - --default-table=${DEFAULT_TABLE:-PrometheusMetricsTable}
      - --region=${AWS_REGION:-us-east-1}
      - --log.level=debug
