Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: timestream-prometheus-connector-advanced
    Description: "This serverless application deploys an AWS Lambda function and an Amazon API Gateway that listens for Prometheus remote write/read requests and stores metrics to Amazon Timestream. This application allows configurations over the resources being created."
    Author: "Amazon Timestream"
    SpdxLicenseId: "Apache-2.0"
    LicenseUrl: "LICENSE"
    ReadmeUrl: "ADVANCED_README.md"
    HomePageUrl: "https://aws.amazon.com/timestream/"
    SemanticVersion: "1.1.0"

Parameters:
  LambdaFunctionName:
    Type: "String"
    Default: "prometheusConnectorLambda"
    Description: "Name of the AWS Lambda function running the connector."
  PrometheusDatabaseLabel:
    Type: "String"
    Default: "prometheusDatabaseLabel"
    AllowedPattern: "[a-zA-Z_][a-zA-Z0-9_]*"
    Description: "The Prometheus label containing the database name."
  PrometheusTableLabel:
    Type: "String"
    Default: "prometheusTableLabel"
    AllowedPattern: "[a-zA-Z_][a-zA-Z0-9_]*"
    Description: "The Prometheus label containing the table name."
  MemorySize:
    Type: "String"
    Default: 512
    AllowedPattern: ([2-9]\d{2,}|[1-9]\d{3,}|1[3-9]\d|12[8-9])
    Description: "The memory size of Lambda function."
  TimeoutInMillis:
    Type: "String"
    AllowedPattern: "^[2-9]|[1-9]\\d+$"
    Default: 15000
    Description: "The amount of time in milliseconds to run the connector on AWS Lambda before timing out."
  ReadThrottlingBurstLimit:
    Type: "String"
    Default: 1200
    Description: "The number of burst requests per second that API Gateway permits."
  WriteThrottlingBurstLimit:
    Type: "String"
    Default: 1200
    Description: "The number of burst requests per second that API Gateway permits."
  RoleName:
    Type: "String"
    Default: "timestreamLambdaRole"
    Description: "The name of the created service role."
  ExecutionPolicyName:
    Type: "String"
    Default: "lambdaBasicExecutionPolicy"
    Description: "The name of the basic execution policy created for AWS Lambda."
  APIGatewayStageName:
    Type: "String"
    Default: "prod"
    Description: "The default stage name of the API Gateway."

Resources:
  IAMLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref "RoleName"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                  - "lambda.amazonaws.com"
                  - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Ref ExecutionPolicyName
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  Fn::Sub: "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionName}:*"

  LambdaFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Role: !GetAtt "IAMLambdaRole.Arn"
      CodeUri: ./timestream-prometheus-connector-linux-amd64-1.1.0.zip
      Description: "Prometheus remote storage connector for Amazon Timestream"
      FunctionName: !Ref "LambdaFunctionName"
      Handler: "timestream-prometheus-connector-linux-amd64-1.1.0"
      MemorySize: !Ref "MemorySize"
      Runtime: "go1.x"
      Environment:
        Variables:
          database_label: !Ref "PrometheusDatabaseLabel"
          table_label: !Ref "PrometheusTableLabel"
      Events:
        WriteApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref APIGateway
            Method: POST
            Path: /write
            TimeoutInMillis: !Ref TimeoutInMillis
            RouteSettings:
              ThrottlingBurstLimit: !Ref "WriteThrottlingBurstLimit"

        ReadApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref APIGateway
            Method: POST
            Path: /read
            TimeoutInMillis: !Ref TimeoutInMillis
            RouteSettings:
              ThrottlingBurstLimit: !Ref "ReadThrottlingBurstLimit"

  APIGateway:
    Type: "AWS::Serverless::HttpApi"
    Properties:
      StageName: !Ref "APIGatewayStageName"

Outputs:
  InvokeWriteURL:
    Description: Remote write URL for Prometheus
    Value:
      Fn::Sub: "https://${APIGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${APIGatewayStageName}/write"
  InvokeReadURL:
    Description: Remote read URL for Prometheus
    Value:
      Fn::Sub: "https://${APIGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${APIGatewayStageName}/read"
  PrometheusDatabaseLabel:
    Description: The Prometheus label containing the database name
    Value:
      !Ref "PrometheusDatabaseLabel"
  PrometheusTableLabel:
    Description: The Prometheus label containing the table name
    Value:
      !Ref "PrometheusTableLabel"
